services:
  - type: web
    name: eureka-server
    env: docker
    plan: free
    dockerfilePath: ./eureka-server/Dockerfile
    autoDeploy: true

  - type: web
    name: api-gateway
    env: docker
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    autoDeploy: true

  - type: web
    name: categoria-service
    env: docker
    plan: free
    dockerfilePath: ./categoria-service/Dockerfile
    autoDeploy: true

  - type: web
    name: producto-service
    env: docker
    plan: free
    dockerfilePath: ./producto-service/Dockerfile
    autoDeploy: true
